### ISSUE TITLE
Add 'rubocop', 'rubocop-rails' to enforce proper formatting and stayling

### ISSUE THREAD

**Issue by tiris08** [IssahBen/cinema#1]
I would highly recommend using rubocop
I guess most ruby/ruby on rails projects use it

here is an example of users_controller and how rubocop fixes it
![image](https://github.com/IssahBen/cinema/assets/62436291/b2d1746b-d896-4523-8259-aa2cc2469677)
the most important here is line 35 where `buybug` command was not removed after debugging, this will cause a bug when updating a user.

**Comment by IssahBen** [comment]
Thank you Taras I will definitely add rubocop-rails .I never knew something like that existed .The byebug on line 35 is an oversight.I will update the repo Asap.Thank you so much

**Comment by tiris08** [comment]
@IssahBen I will add more feedback after you add rubocop
You could also add changes through github pull requests this will prepare you for real-world projects where you work in a team.
generally for any new feature or a bug fix you create a pull request when working in a team(shared repository)
for example in this case:
- create a new git branch called 'robocop'
- implement rubocop setup and run rubocop command to correct all offenses
- when done, push a branch to github and create a pull request for that branch
Then when pull request is ready you can request a review from me.

**Comment by IssahBen** [comment]
I successfully added the rubocop gem and  corrected all the offences .I have pushed the robocop branch to GitHub  and created a pull request.I think before I can assign you as a reviewer  to the pull request I have to add you as a collaborator  so I sent an invite to make you collaborator after you accept I think I can add you as a reviewer.

**Comment by tiris08** [comment]
#2
