### ISSUE TITLE
Bug on Edit Account Details page

### ISSUE THREAD

**Issue by tiris08** [IssahBen/cinema#3]
I can't update my account details

the form validation confuses username field with email field

![image](https://github.com/IssahBen/cinema/assets/62436291/c7abebf0-440e-416d-b83d-836484ad9f57)

**Comment by IssahBen** [comment]
I think I used an f.email_field in that place I will change it asap .

**Comment by IssahBen** [comment]
Taras I have fixed the bug  and pushed the changes to heroku.You can now update the account details.
Thanks

**Comment by tiris08** [comment]
#2
